GH-1631: fix missing @SendTo for cglib proxies
spring-projects/spring-kafka pull request #1632
Opened 2020-11-19 01:41 UTC by radiment

Use handler.getBeanType() instead of bean.getClass(). Due to bean could be cglib proxy bean.

2020-11-19 01:41 UTC, pivotal-issuemaster commented
@radiment Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=1632)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=1632) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-11-19 01:42 UTC, pivotal-issuemaster commented
@radiment Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=1632)!

2020-11-19 15:05 UTC, artembilan requested changes

2020-11-19 15:05 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
> +			Class<?> beanType = handler.getBeanType();
I think we can reach the same solution just using a `ClassUtils.getUserClass()`.
But it's OK what you provide so far.
Now we need a test-case to prove the issue and fix for it.

Thanks

2020-11-23 15:58 UTC, garyrussell commented
Thanks; merged as 90b9f625 after fixing checkstyle (imports).

2020-11-23 15:58 UTC, closed without merging

2020-11-23 18:31 UTC, garyrussell commented
Cherry-picked to 2.5.x, 2.4.x, 2.3.x.