GH-1744: Improve KafkaConsumerBackoffManager dependency management
spring-projects/spring-kafka pull request #1756
Opened 2021-04-05 01:22 UTC by tomazfernandes

Resolves #1744
Introduces the KafkaConsumerTimingAdjuster interface
Introduces the KafkaBackOffManagerFactory interface

2021-04-05 01:30 UTC, tomazfernandes commented
This ended up being a larger PR than I anticipated - although mostly new code. If it's too close to RC2 for you to review I don't mind if it goes into the next release.

Thanks!

2021-04-05 15:01 UTC, garyrussell requested changes
Just some minor polishing needed.

2021-04-05 15:01 UTC, garyrussell commented on spring-kafka/src/test/java/org/springframework/kafka/listener/WakingKafkaConsumerTimingAdjusterTest.java
> +class WakingKafkaConsumerTimingAdjusterTest {
Convention is `...Tests`

2021-04-05 23:36 UTC, tomazfernandes commented on spring-kafka/src/main/java/org/springframework/kafka/listener/TimingAdjustingKafkaBackOffManagerFactory.java
> +		this.setTimingAdjustmentManager(timingAdjustmentManager);
Actually I needed to call this() to instantiate the default clock, but I guess it's better to do that explicitly.

2021-04-06 00:12 UTC, tomazfernandes commented
> Just some minor polishing needed.

@garyrussell changes made, please let me know if there's anything else. Thanks!

2021-04-07 13:10 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/listener/TimingAdjustingKafkaBackOffManagerFactory.java
> +	final public void setTimingAdjustmentManager(KafkaConsumerTimingAdjuster timingAdjustmentManager) {
`public final` - will fix on merge.

2021-04-07 15:19 UTC, garyrussell commented
Merged as 290d11a319145a741303f6affcff23ff66ee57d2 with minor polishing.

2021-04-07 15:19 UTC, closed without merging

2021-04-08 00:47 UTC, tomazfernandes commented
Thanks a lot @garyrussell! 🙏🏼