Data in handle method is @Nullable
spring-projects/spring-kafka pull request #1837
Opened 2021-06-21 13:05 UTC by kkocel

Motivation - Kotlin uses jsr305 annotations to deduct non-null / nullable types. This PR marks data as explicitly nullable (which happen in code)

2021-06-21 15:26 UTC, artembilan requested changes
Please, fix Checkstyle issue: 
```
Error: eckstyle] [ERROR] /home/runner/work/spring-kafka/spring-kafka/spring-kafka/src/main/java/org/springframework/kafka/listener/BatchLoggingErrorHandler.java:26:1: Extra separation in import group before 'org.springframework.lang.Nullable' [ImportOrder]
```

You can check it locally with Gradle `check` task.

Thanks

2021-06-21 20:00 UTC, kkocel commented
@artembilan Hi, fixed right away. Sorry for inconvienience.

2021-06-21 20:32 UTC, artembilan approved these changes
I'm OK with this change: doesn't look like it breaks something.
Although I have doubts if we should propagate something reasonable in those default methods instead of `null`.

Let's see what @garyrussell thinks on the matter!

2021-06-21 20:45 UTC, garyrussell commented
@kkocel Under what circumstances are you seeing it being called with `null` values?

Even with consumer exceptions (before we receive any `ConsumerRecords`), the container calls it with empty objects.

https://github.com/spring-projects/spring-kafka/blob/e624891e424a28a53ea95081c742c1d566b94f52/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1597-L1605

This is misleading...

https://github.com/spring-projects/spring-kafka/blob/e624891e424a28a53ea95081c742c1d566b94f52/spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandler.java#L39-L41

All error handlers provided by the framework implement this method so it is never called.

2021-06-22 09:08 UTC, delor commented
If you implement `ErrorHandler` in Kotlin like so
```kotlin
import org.apache.kafka.clients.consumer.ConsumerRecord
import org.springframework.kafka.listener.ErrorHandler
import java.lang.Exception

class MyErrorHandler : ErrorHandler {
    override fun handle(thrownException: Exception, data: ConsumerRecord<*, *>) {
        TODO("Not yet implemented")
    }
}
```
parameter `data` can be null b/c of `@NonNullApi`. Then `org.springframework.kafka.listener.ErrorHandler#handle` will pass null to it and you will get exception in runtime b/c `data` parameter in `MyErrorHandler` can't be null.

2021-06-22 11:09 UTC, kkocel commented
@garyrussell having proper annotations is crucial for having proper types in Kotlin, as you can run into a problem @delor stated. More info here: https://www.youtube.com/watch?v=DvqXdnzhlSc&t=622s

2021-06-22 12:49 UTC, artembilan commented
Thank you for the patience, @kkocel, and info!

May you share with us a stack trace for this issue to have a whole picture?
We definitely can live with your change since it is not a breaking change for Java at all.
At the same time it makes Kotlin happy.

Nevertheless I still think that we may revise those `default` method impls, but that already going to some breaking change in the API. Therefore next framework version.

2021-06-22 12:56 UTC, garyrussell commented
>crucial for having proper types in Kotlin,

I fully understand that.

I believe we should deprecate that method; users should always implement `ContainerAwareErrorHandler` or `ConsumerAwareBatchErrorHandler` since the container always calls the method with 3 parameters.

Making it `@Nullable` seems wrong to me since it will never be called with a `null` value by the container.

2021-06-22 16:12 UTC, delor commented
Sorry, can't provide a stacktrace as we have moved on with different approach and can't recreate it.

2021-06-22 16:25 UTC, garyrussell commented
I have tried several different ways to fix this in a non-breaking way without success, so I think I will go ahead and merge this; thanks for the contribution.

I have re-opened this issue https://github.com/spring-projects/spring-kafka/issues/615 so we can rework this error handler hierarchy in a breaking way in 3.0.

2021-06-22 17:01 UTC, merged