Updated the DefaultKafkaProducerFactory to support producer configs overrides
spring-projects/spring-kafka pull request #2075
Opened 2022-01-17 21:53 UTC by frosiere

The DefaultKafkaProducerFactory has been updated to support producer config overrides as described in the issue #2070.

Two protected methods have been created to allow retrieving the configs of transactional and non-transactional producers.
These methods can be overridden in case of override.

2022-01-25 15:30 UTC, garyrussell requested changes
Thanks for the contribution! LGTM; just one comment.

In future, please restrict the first line of the commit comment to 50 chars (see the contribution guidelines).

Add `Resolves https://github.com/spring-projects/spring-kafka/issues/2070` to the next commit so that the issue will automatically close when this is merged.

2022-01-25 15:30 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
> +	protected Map<String, Object> getProducerConfigs() {
`protected` methods require javadocs.

2022-01-25 20:12 UTC, frosiere commented
> Thanks for the contribution! LGTM; just one comment.
> 
> In future, please restrict the first line of the commit comment to 50 chars (see the contribution guidelines).
> 
> Add `Resolves https://github.com/spring-projects/spring-kafka/issues/2070` to the next commit so that the issue will automatically close when this is merged.

Thanks for the review.
Missing javadoc has been added.

2022-01-26 17:13 UTC, garyrussell commented
Thanks; merged as 0fc1548dd49920fc8867fa6a1e299c95df5cc659 cherry-picked as b669c12df7358ef35f542090b07d7bc9bed40149

2022-01-26 17:13 UTC, closed without merging