GH-2049: Spring Managed Producer Interceptors
spring-projects/spring-kafka pull request #2112
Opened 2022-02-17 21:55 UTC by sobychacko

Allow producer interceptors to be managed by Spring so that
they can be used in KafkaTemplate instead of providing the classname
of the interceptor to Kafka configuraiton.

Adding tests and docs.

Resolves https://github.com/spring-projects/spring-kafka/issues/2049

2022-02-17 22:22 UTC, artembilan requested changes
Just one nit-pick.

👍

2022-02-18 20:03 UTC, garyrussell commented
It is not important if this misses Tuesday's M2 release.

2022-02-18 23:34 UTC, sobychacko commented on spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
> +			this.producerInterceptor.onSend(producerRecord);
It looks like Kafka's `ProducerInterceptors` simply log the exception from individual interceptors and continue. See [here](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerInterceptors.java#L62). The one set on the `KafkaTemplate` can be used to cancel if need be. I was thinking maybe with a `CompositeProducerInterceptor` we can follow the same approach used in Kafka's `ProducerInterceptors`.

2022-02-22 16:46 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/support/CompositeProducerInterceptor.java
> +					CompositeProducerInterceptor.this.logger.warn(e, () -> "Error executing interceptor onSend callback");
Maybe add `interceptor.toString()` to these log messages?

2022-02-23 20:37 UTC, garyrussell approved these changes

2022-02-23 20:37 UTC, merged