GH-2134: Add filter to @KafkaListener
spring-projects/spring-kafka pull request #2138
Opened 2022-02-24 20:02 UTC by garyrussell

Resolves https://github.com/spring-projects/spring-kafka/issues/2134

Also clean up parsing of `errorHandler` and `contentTypeConverter`.

**cherry-pick to 2.8.x**

2022-02-24 22:42 UTC, tomazfernandes commented on spring-kafka-docs/src/main/asciidoc/kafka.adoc
> +Starting with version 2.8.4, you can override the listener container factory's default `RecordFilterStrategy` by using the `filter` property on the listner.
Typo: listener

2022-02-24 22:46 UTC, tomazfernandes commented on spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
>  	private void processKafkaListenerAnnotationForRetryTopic(MethodKafkaListenerEndpoint<?, ?> endpoint,
Maybe we can lose this method and take off the "beforeRegistration" part of the other, since now there's no "after"?

2022-02-24 22:55 UTC, tomazfernandes approved these changes
Well, I ended up reviewing the PR, and it looks great to me, so I'll leave my symbolic approval, with only those cosmetic comments. Thanks.

2022-03-02 14:47 UTC, garyrussell commented
Do not merge yet: https://github.com/spring-projects/spring-kafka/issues/2134#issuecomment-1057011222

2022-03-04 20:19 UTC, artembilan requested changes

2022-03-04 20:19 UTC, artembilan commented on spring-kafka-docs/src/main/asciidoc/whats-new.adoc
> +The `@KafkaListener` annotation now the "info" attribute; this is used to populate the new listener container property `listenerInfo`.
Missed `has`: 
```suggestion
The `@KafkaListener` annotation now has the `info` attribute; this is used to populate the new listener container property `listenerInfo`.
```

2022-03-04 20:19 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
> +	 * {@link org.springframework.kafka.listener.RecordInterceptor}, {@link RecordFiorg.springframework.kafka.listener.adapter.RecordFilterStrategylterStrategy} or the listener itself, for
Typo for the `RecordFilterStrategy`:
```suggestion
	 * {@link org.springframework.kafka.listener.RecordInterceptor}, {@link org.springframework.kafka.listener.adapter.RecordFilterStrategy} or the listener itself, for
```

2022-03-04 20:19 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
> +	 * must resolve to a String or `byte[]`.
I think you mean this:
```suggestion
	 * must resolve to a String or {@code byte[]}.
```

2022-03-04 20:19 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
> +				record.headers().add(this.infoHeader);
Why cannot we do conversion to `byte[]` over here?
I mean that is really just an `info`, so end-users will expect from us a plain `public void setListenerInfo(@Nullable String listenerInfo) {` from the configuration side.

2022-03-04 20:19 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/support/KafkaHeaders.java
> +	 * Arbitrary static information about the listener receiving this record.
`@since 2.8.4`
?

2022-03-07 17:57 UTC, merged