GH-2252: Keep offset metadata in case of batch reprocessing
spring-projects/spring-kafka pull request #2253
Opened 2022-05-03 22:53 UTC by frosiere

Remarks:

- Every OffsetAndMetadata are now created using the provider if available. 
- Listener info has been added to the MessageListener container interface.
- Code related to the provider has been refactored and simplified.
- Javadoc has been reviewed.

Closes #2252

2022-05-04 13:37 UTC, artembilan requested changes
Please, add your name to the `@author` list of all the affected classes.
When it missed yet, of course.

Otherwise this is OK with me even if those minor concerns.

Thank you!

2022-05-04 16:09 UTC, garyrussell requested changes
Just one minor nit.

2022-05-04 21:04 UTC, frosiere commented on spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultListenerMetadata.java
> +		this.container = container;
Check has been added.

2022-05-04 21:04 UTC, frosiere commented on spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultListenerMetadata.java
> +public class DefaultListenerMetadata implements ListenerMetadata {
Removed the public modifier.

2022-05-04 21:05 UTC, frosiere commented on spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
> +	 * @since 2.8.4
Updated the version.

2022-05-04 21:36 UTC, artembilan requested changes

2022-05-04 21:36 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
> +	private OffsetAndMetadata createOffsetAndMetadata(@Nullable MessageListenerContainer container, long offset) {
`static`

2022-05-05 18:52 UTC, frosiere commented on spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
> +	private OffsetAndMetadata createOffsetAndMetadata(@Nullable MessageListenerContainer container, long offset) {
Missing static keyword added.

2022-05-05 18:53 UTC, artembilan approved these changes

2022-05-06 14:25 UTC, frosiere commented
Any review remarks have been applied. If something else is required, please let me know.

2022-05-09 13:57 UTC, garyrussell approved these changes

2022-05-09 13:58 UTC, merged

2022-05-09 15:02 UTC, garyrussell commented
Many thanks for the contribution.