Add BackOffHandler to FailedRecordTracker
spring-projects/spring-kafka pull request #2263
Opened 2022-05-06 07:35 UTC by Marincek

Added new BackOffHandler interface. The idea is to decouple the FailedRecordTracker with the behavior on next back off time. 
Currently the FailedRecordTracker is sleeping the thread, and there is now way to change that behaviour.

Related issue : https://github.com/spring-projects/spring-kafka/issues/2262

2022-05-06 07:35 UTC, pivotal-cla commented
@Marincek Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=2263)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=2263) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-05-06 07:36 UTC, pivotal-cla commented
@Marincek Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=2263)!

2022-05-06 08:55 UTC, selalerercapitolis approved these changes

2022-05-06 14:31 UTC, artembilan requested changes
I wonder if existing `KafkaConsumerBackoffManager` abstraction can work here as well, without introducing anything else...

@tomazfernandes, WDYT ?

2022-05-09 15:06 UTC, garyrussell commented
@artembilan That is for pausing a single partition, in this case we need to pause the entire container.

@Marincek Are you planning on providing the implementation that pauses and resumes the container?

2022-05-09 15:28 UTC, tomazfernandes commented
> I wonder if existing `KafkaConsumerBackoffManager` abstraction can work here as well, without introducing anything else...
> 
> @tomazfernandes, WDYT ?

Missed this notification, sorry @artembilan. As @garyrussell pointed out, the `KafkaConsumerBackOffManager` is meant to back off a single partition, but we probably could just retrieve all assignments for that container and loop through them. 

One important thing is we need to make sure a `idlePartitionEventInterval` is set for the container - maybe we could look into providing a default value for that.

Now that you brought this up, and considering this `pause until` pattern appears here and there, I think in the future we might look into leveraging the `BackOffManager` to handle all such logic - the `nack` feature comes to mind as well for example - so that we don't need to implement it over and over again and have a centralized place to handle all partitions. Maybe we could auto configure a `BackOffManager` bean for that and inject where needed.

But I defer to @garyrussell what would be the proper solution for this particular case.

2022-05-09 15:42 UTC, garyrussell commented
@Marincek use `./gradlew check` to build the project (including running checkstyle).

2022-06-27 17:18 UTC, garyrussell commented
Sorry for the delay; I have squashed and merged your commits to this branch https://github.com/garyrussell/spring-kafka/tree/GH-2262

with this polishing commit: https://github.com/garyrussell/spring-kafka/commit/17f8f85d8c532268fa17ba506bfd23be388f5389

I will merge both after my commit is reviewed by @artembilan

2022-06-27 18:45 UTC, garyrussell commented
Merged and cherry-picked; thanks for the contribution!

2022-06-27 18:45 UTC, closed without merging