GH-2284: Publish Auth Error Events
spring-projects/spring-kafka pull request #2317
Opened 2022-06-23 10:56 UTC by danielgentes

* Added Events for auth failed
and successful retry of auth
* publish of these events
* unit testing

Closes #2284

2022-06-23 18:07 UTC, garyrussell requested changes
Thanks!

Just a few minor nits.

2022-06-23 18:07 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java
> + * Copyright 2018-2022 the original author or authors.
New files only need 2022.

2022-06-23 18:07 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java
> + * An event published when authentication or authorization of a consumer fails and is being retried. Contains the triggering throwable.
Please wrap javadocs at 90 chars (code at 120).

2022-06-23 18:07 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java
> +	 * Return the reason why the consumer was stopped.
Looks like copy/paste.

Return the reason for the auth failure.

2022-06-23 18:07 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java
> +	 * @since 2.5.8
```suggestion
	 * @since 2.8.8
```

2022-06-23 18:07 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthSuccessfulEvent.java
> + * Copyright 2018-2022 the original author or authors.
2022

2022-06-24 06:16 UTC, danielgentes commented
Hi @garyrussell,
thank you for the review! I addressed the mentioned changed in my latest commit.

2022-06-24 14:34 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
> +	private void publishRetryAuthEvent(Throwable throwable) {
Please, add your name to the `@author` list: you have made some changes to the class, so you deserve some credit.

2022-06-24 17:36 UTC, danielgentes commented
Hi @artembilan ,
thanks for the review! I updated the documentation and also made the other changes you suggested.

2022-06-24 17:55 UTC, merged