GH-2332: Fix Container.pause() with Manual Assign.
spring-projects/spring-kafka pull request #2333
Opened 2022-07-06 19:46 UTC by garyrussell

Resolves https://github.com/spring-projects/spring-kafka/issues/2332

Use manual assignments, if present for pause.
Also, in the rebalance listener, use `isPaused()` rather than `consumerPaused`
to determine whether the partitions should be paused.

Add logs and events for pauses in the rebal listener.

**cherry-pick to 2.9.x, 2.8.x**

2022-07-06 20:43 UTC, artembilan requested changes

2022-07-06 20:43 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
> +				if (!CollectionUtils.isEmpty(assigned)) {
I guess this one has to come together with an `import org.springframework.util.CollectionUtils;`

2022-07-06 21:15 UTC, merged

2022-07-07 00:18 UTC, artembilan commented
Cherry-picked to `2.9.x`, but it doesn't back-port clear to `2.8.x`.
No `pauseForPending` in the `KafkaMessageListenerContainer` and no `DefaultErrorHandler.setSeekAfterError()` used in the `PauseContainerManualAssignmentTests`.
Thanks

2022-07-07 13:57 UTC, garyrussell commented
Back ported to 2.8.x; found a problem during the back port - fixed there, as well as on main and 2.9.x a63359c1