GH-2198: Spring Observability Initial Commit
spring-projects/spring-kafka pull request #2394
Opened 2022-09-15 14:05 UTC by garyrussell

Resolves https://github.com/spring-projects/spring-kafka/issues/2198

2022-09-15 14:06 UTC, garyrussell commented
<img width="977" alt="Screen Shot 2022-09-15 at 10 03 22 AM" src="https://user-images.githubusercontent.com/483832/190424935-a5111ab2-58a0-4fea-a11f-ee0cf44b8c81.png">

2022-09-15 18:40 UTC, artembilan requested changes

2022-09-15 18:40 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/DefaultKafkaListenerObservationConvention.java
> +		return KeyValues.empty();
It looks like `default` method on the `ObservationConvention` does exactly the same

2022-09-15 18:40 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaTemplateObservation.java
> +				return "bean.name";
In Spring Integration PR @marcingrzejszczak has requested me to add a meaningful prefix to all the tags I expose on the observation: https://github.com/spring-projects/spring-integration/pull/3879#pullrequestreview-1104184375.
So, probably this one should go as a `spring.kafka.template.name` ?

2022-09-15 18:40 UTC, artembilan commented on spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
> +@EmbeddedKafka(topics = { "observation.testT1", "observation.testT2" })
`@DirtiesContext` to stop an embedded broker in the end?

2022-09-15 19:00 UTC, artembilan approved these changes

2022-09-15 19:59 UTC, garyrussell commented
With async stop...

<img width="1081" alt="Screen Shot 2022-09-15 at 3 58 53 PM" src="https://user-images.githubusercontent.com/483832/190497548-36bdbd56-d763-4ae7-aefd-1185fb63b9d7.png">

2022-09-16 14:02 UTC, artembilan requested changes
This one still fails on the GH actions.
Probably because of that async `stop()` feature you try to incorporate.

@marcingrzejszczak,

would you mind to look into this PR as well?
Should be similar to what we have so far in Spring AMQP.

Thank you!

2022-09-16 19:40 UTC, marcingrzejszczak requested changes
I've found 2 minor issues, other than that LGTM.

The question is if you want to use the automated documentation generation - https://micrometer.io/docs/tracing#_documentation_building , that way all of your observations would be automatically scanned and an adoc file will be created cc @artembilan

2022-09-16 19:40 UTC, marcingrzejszczak commented on spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaRecordReceiverContext.java
> +	public String getName() {
Don't set the name here - please set it via the convention

2022-09-16 19:40 UTC, marcingrzejszczak commented on spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaRecordSenderContext.java
> +		return "spring.kafka.template";
Don't set the name here - please set it via the convention

2022-09-19 17:38 UTC, merged