Remove outdated information for transactional.id
spring-projects/spring-kafka pull request #2524
Opened 2023-01-02 10:12 UTC by LukasHeimann

Compare https://github.com/spring-projects/spring-kafka/issues/2515

With only EOSMode v2 supported, the alternative way of `transactional.id` creation is not used anymore and not needed anymore. This PR removes the outdated (and confusing) extra documentation in the overview section for transactions.

2023-01-02 10:21 UTC, LukasHeimann reviewed
The PR currently only includes the minimum necessary change to remove the outdated documentation.

However, I propose to also add two additional sentences of clarification that might be helpful for readers (at least I would have been happy to have them) -- if you feel like they should be included, please let me know or just accept the suggested change.

1. Information on how the transactional.id was generated differently in the past. This is useful, as there are many old posts around that discuss this old behavior, so just giving a heads up that you don't have to care is probably nice
2. Information on `transactionIdPrefix` having to be unique per instance of an application. This is mixed up in the discussion of the old way of generation as well: for consumer-initiated transactions it used to be that the `transactionIdPrefix` should be the same for multiple instances, for producer-initiated it must be different. Hence, a small sentence of explanation is probably helpful as well.

2023-01-02 10:21 UTC, LukasHeimann commented on spring-kafka-docs/src/main/asciidoc/kafka.adoc
> +The `transactional.id` property of each producer is `transactionIdPrefix` + `n`, where `n` starts with `0` and is incremented for each new producer.
```suggestion
The `transactional.id` property of each producer is `transactionIdPrefix` + `n`, where `n` starts with `0` and is incremented for each new producer.
In previous versions of Spring Kafka, the `transactional.id` was generated differently for transaction started by a listener container with a record-based listener to support fencing zombies, which is not necessary anymore with EOSMode V2 being the only option starting with 3.0.0.
For applications running with multiple instances, the `transactionIdPrefix` should be unique per instance.
```

2023-01-09 18:06 UTC, garyrussell requested changes
Thanks! Just a couple of small comments

2023-01-09 18:06 UTC, garyrussell commented on spring-kafka-docs/src/main/asciidoc/kafka.adoc
> +For applications running with multiple instances, the `transactionIdPrefix` should be unique per instance.
```suggestion
In previous versions of Spring for Apache Kafka, the `transactional.id` was generated differently for transactions started by a listener container with a record-based listener, to support fencing zombies, which is not necessary any more, with `EOSMode.V2` being the only option starting with 3.0.
For applications running with multiple instances, the `transactionIdPrefix` must be unique per instance.
```

2023-01-09 18:56 UTC, garyrussell approved these changes

2023-01-09 18:56 UTC, merged