GH-2377: Add DestinationTopic.Properties#isRetryTopic()
spring-projects/spring-kafka pull request #2589
Opened 2023-02-17 14:55 UTC by echo304

Resolve https://github.com/spring-projects/spring-kafka/issues/2377

`DestinationTopic.Properties` has `isDltTopic()` and `isMainEndpoint()` but not for retry topic. It adds `isRetryTopic()` method and adds tests to verify the correct behavior.

* Add `isRetryTopic()` instance method to `DestinationTopic.Properties`

2023-02-23 20:24 UTC, garyrussell requested changes
Thanks for the contribution; please run `./gradlew clean check` to run checkstyle rules.

2023-02-23 20:24 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopic.java
> +		public boolean isRetryTopic() { return Type.RETRY.equals(this.type) || Type.SINGLE_TOPIC_RETRY.equals(this.type); }
```suggestion
		public boolean isRetryTopic() {
			return Type.RETRY.equals(this.type) || Type.SINGLE_TOPIC_RETRY.equals(this.type);
		}
```

2023-02-24 06:28 UTC, echo304 commented on spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopic.java
> +		public boolean isRetryTopic() { return Type.RETRY.equals(this.type) || Type.SINGLE_TOPIC_RETRY.equals(this.type); }
Thank you for pointing it out!

2023-02-24 06:31 UTC, echo304 commented on spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopic.java
> +		public boolean isRetryTopic() { return Type.RETRY.equals(this.type) || Type.SINGLE_TOPIC_RETRY.equals(this.type); }
Fixed! 👍

2023-02-27 19:17 UTC, merged