GH-2825: Provide a way to customize a single listener
spring-projects/spring-kafka pull request #2851
Opened 2023-10-16 20:00 UTC by frosiere

Sorry for the delay. Documentation has not been updated as I didn't know were to put this new feature. 

The ContainerPostProcessor support has been added. This one can be used in addition to the ContainerCustomizer. As the post processor is more specific, it will be applied after the customizer to allow fine grained customization per container.

Let me know if you have any remarks and I will update accordingly. Thanks.

Resolves https://github.com/spring-projects/spring-kafka/issues/2825

2023-10-16 20:32 UTC, garyrussell commented
No problem; thanks; will review when I get back on Wednesday; one quick comment is that we wrap Javadoc lines to 90 chars and code lines at 120 chars.

I think we just need to add a small mention at the end of this section:

https://github.com/spring-projects/spring-kafka/blob/61bc2190eb592515e95d322f6d16b359cb5134d0/spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-factory.adoc?plain=1#L27-L39

2023-10-18 15:52 UTC, garyrussell requested changes
LGTM; thanks!

Just some minor comments - mostly nit-picks, conventions.

2023-10-18 15:52 UTC, garyrussell commented on spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-factory.adoc
> +'ContainerPostProcessor' on the KafkaListener annotation.
Our convention is one line per sentence.

2023-10-18 15:52 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
> +	 * @since 3.1.0
```suggestion
	 * @since 3.1
```

2023-10-18 15:52 UTC, garyrussell commented on spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-factory.adoc
> +Starting with version 3.1.0, it's also possible to apply the same kind of customization on a single listener by specifying the bean name of a
```suggestion
Starting with version 3.1, it's also possible to apply the same kind of customization on a single listener by specifying the bean name of a
```
We only use `x.y.z` when `z` is greater than zero.

Also add a paragraph to `../whats-new.adoc`.

2023-10-18 15:52 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
> +	 * listener containers.
```suggestion
	 * listener containers. This post processor is applied after the container customizer (if present).
```

2023-10-18 15:52 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/config/ContainerPostProcessor.java
> + * containers.
```suggestion
 * containers. In that case, this will be applied after the customizer.
```

2023-10-18 15:52 UTC, garyrussell commented on spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpoint.java
> +	 * @since 3.1.0
```suggestion
	 * @since 3.1
```

2023-10-18 19:52 UTC, frosiere commented
Thanks for the review. All remarks have been addressed. Let me know if I need to adapt something else.

2023-10-19 16:26 UTC, garyrussell approved these changes

2023-10-19 16:31 UTC, garyrussell commented
Great; thanks! Merged as 4862d6a64

2023-10-19 16:31 UTC, closed without merging