GH-2654: Incorrect retry topic suffix
spring-projects/spring-kafka pull request #2876
Opened 2023-11-02 14:36 UTC by Wzy19930507

Resolves https://github.com/spring-projects/spring-kafka/issues/2654

* fix incorrect retry topic suffix when attempts is 2

* optimization method `isDelayWithReusedTopic`

* add retry topic integration tests when reuse retry topic

fix java doc in RetryTopic

* fix javadoc in `@RetryTopic`

* fix javadoc in `RetryTopicConfigurationProvider`

2023-11-06 18:24 UTC, artembilan approved these changes
This is OK with me, but we still need @garyrussell 's approval.

And I guess since we have a workaround for older versions, we are not going to back-port the fix since it feels a bit as a breaking change.

Thanks

2023-11-07 08:56 UTC, Wzy19930507 commented
Thanks for your review 💯

2023-11-14 15:09 UTC, garyrussell requested changes
LGTM, but we should add a note to the `whats-new.adoc` about the behavior change - users will somehow need to migrate any messages in the "old" retry topic.

On the other hand, maybe the new behavior needs to be an opt-in property, to avoid the need for such migration.

We are getting close to GA (next week); if we decide to go with the opt-in approach, it would be ok to move it to 3.1.1.

2023-11-15 02:46 UTC, Wzy19930507 commented
> On the other hand, maybe the new behavior needs to be an opt-in property, to avoid the need for such migration.

May we use this case replacement opt-in?
```
@RetryableTopic(
        backoff = Backoff(delay = 5000),
        attempts = "2",
        autoCreateTopics = "false",
        fixedDelayTopicStrategy = FixedDelayStrategy.SINGLE_TOPIC
        
    )
```

2023-11-15 15:55 UTC, garyrussell approved these changes

2023-11-15 15:55 UTC, garyrussell commented on spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
> +See xref:retrytopic/topic-naming.adoc[Topic Naming] for more information.
```suggestion
Change suffix `-retry-5000` to `-retry` when `@RetryableTopic(backoff = @Backoff(delay = 5000), attempts = "2", fixedDelayTopicStrategy = FixedDelayStrategy.SINGLE_TOPIC)`.
If you want to keep suffix `-retry-5000`, use `@RetryableTopic(backoff = @Backoff(delay = 5000), attempts = "2")`.
See xref:retrytopic/topic-naming.adoc[Topic Naming] for more information.
```

2023-11-15 15:55 UTC, garyrussell commented
Thanks!

Please rebase to main to address conflicts.

2023-11-15 17:58 UTC, Wzy19930507 commented
Thanks you for review : )

2023-11-16 18:54 UTC, merged