cosmetic doc improvements part 4
spring-projects/spring-kafka pull request #2879
Opened 2023-11-04 05:00 UTC by NathanQingyangXu

final part. feel free to change.

2023-11-06 16:50 UTC, artembilan requested changes
Just a couple questions.
Thanks

2023-11-07 01:07 UTC, NathanQingyangXu commented on spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/sequencing.adoc
> += Starting `@KafkaListener`s in Sequence
a mistake. updated. thx

2023-11-07 01:10 UTC, NathanQingyangXu commented on spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/topic-naming.adoc
> +"my-topic" +++->+++ "my-topic-retry-0", "my-topic-retry-1", ..., "my-topic-dlt"
I thought the special arrow rending seems not intended and the "raw" text seems more desirable. Reverted back.

2023-11-07 04:03 UTC, NathanQingyangXu commented on spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/topic-naming.adoc
> +"my-topic" +++->+++ "my-topic-retry-0", "my-topic-retry-1", ..., "my-topic-dlt"
I also reverted back a similar change commited previously: https://github.com/spring-projects/spring-kafka/pull/2879/commits/83d1eafcb5d07f5b9bcf3127ec2a23f9440de170

2023-11-07 14:30 UTC, merged