Gh-2924 Fix send null payload with KafkaTemplate#send(Message), and …
spring-projects/spring-kafka pull request #2925
Opened 2023-12-07 17:07 UTC by pswrdf

…JsonMessageConverter

fixes: https://github.com/spring-projects/spring-kafka/issues/2924

2023-12-07 17:08 UTC, pivotal-cla commented
@pswrdf Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=2925)!

2023-12-07 17:11 UTC, sobychacko commented
@pswrdf Thanks for the PR! Can you add a unit test to verify the changes? Or point to an existing test where this code is exercised.

2023-12-07 17:36 UTC, artembilan requested changes
Hi @pswrdf !

Thank you for contribution.
Please, make yourself familiar with commit message rules we try to follow: https://cbea.ms/git-commit/.

I don't say that you need to change anything right now if you don't want, but just for the future to avoid comments from me like this 😉 

@sobychacko ,

This fix is supposed to be back-ported to `3.0.x`.
When you merge this, please, consider to include `Fixes: gh-2924` like into commit message.
This way Backport Bot GHA workflow will create a respective back-port issue for for current `3.0.x` milestone. However don't merge yet, please, I'm working in that branch right now to migrate it into GHA.

2023-12-07 18:50 UTC, artembilan requested changes
So, now CI/CD infra is set up for `3.0.x`.
Therefore we are good to cherry-pick after merging this.

1. Add some unit test, please. See `BatchListenerConversionTests` where we use one of those `JsonMessageConverter` impls.
2. Add your name to the `@author` list of all the affected classes.
3. Add also `Fixes: gh-2924` into next commit message as I asked before.
4. Add `**Cherry-pick to `3.0.x`**` into the next commit message.

Thanks

2023-12-07 22:55 UTC, sobychacko commented on spring-kafka/src/main/java/org/springframework/kafka/support/converter/JsonMessageConverter.java
Missing `author` tag in this class.

2023-12-07 22:59 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/support/converter/JsonMessageConverter.java
There is no need. 
This class has lost its changes.

2023-12-07 23:08 UTC, pswrdf commented on spring-kafka/src/main/java/org/springframework/kafka/support/converter/JsonMessageConverter.java
it was reverted in the second commit.

I think it's done.

2023-12-07 23:35 UTC, pswrdf commented
I think it's done.

Would I squash commits? It needs to change email also.

2023-12-08 15:43 UTC, merged

2023-12-08 18:37 UTC, artembilan commented
... and cherry-picked to `3.0.x`