GH-3067: Draft of mapping multiple headers with same key
spring-projects/spring-kafka pull request #3101
Opened 2024-03-05 15:52 UTC by poznachowski

Draft of mapping iterable headers

2024-03-05 18:14 UTC, artembilan requested changes
I'm OK with the solution.
Please, consider to run `gradlew check` locally, so you will see Checkstyle violations.
Thanks

2024-03-05 18:17 UTC, artembilan requested changes
Please, also add your name to the `@author` list of the affected classes.
The `whats-new.adoc` deserves a new entry for this new feature.
And `headers.adoc` must be improved about this new behavior.

I also see that you did nothing for the `DefaultKafkaHeaderMapper`.
Probably the logic you have introduced can go into the `AbstractKafkaHeaderMapper` ?

2024-03-05 19:07 UTC, poznachowski commented
Yes of course. This was just a starter to make sure I'm on the right track.

2024-03-11 18:55 UTC, sobychacko commented
@poznachowski, Any updates on this? We have a release coming up next week. If you want this to be part of that release, we need to start further review on this PR sooner.

2024-03-11 22:52 UTC, poznachowski commented
I should have something ready tomorrow.

2024-03-12 22:21 UTC, poznachowski commented
I updated my MR with initial version (not polished) of `DefaultHeaderKafkaMapper`. It's more complicated than I thought.
The need of handling `spring_json_header_types` header makes it harder to extract common logic to the `AbstractKafkaHeaderMapper`.
I'm not really sure if my solution will hold. I see that `RecordHeaders` uses `List` internally, but is it enough to guarantee that Kafka ensures headers order?
Additionally, the change makes `DeliveryHeaderTests` fail. `retry_topic-attempts` header becomes now a list with 2 entries and `getNonBlockingRetryDeliveryAttempt` method fails. Haven't investigated it yet.

2024-03-14 20:45 UTC, sobychacko commented
@poznachowski We moved the milestone to `3.2.0-RC1`, which is the April release, so you have some time to polish things. Please let us know when it is ready for the actual review. The approach that you take in the PR is in the right direction. Could you polish and make sure that there are no checkstyle issues, etc.? Then we will do more formal reviews.

2024-03-14 21:29 UTC, poznachowski commented
@sobychacko sure, should have it ready somewhere beginning next week.

2024-03-25 14:52 UTC, sobychacko commented
@poznachowski Any updates on this PR?

2024-03-29 11:35 UTC, poznachowski commented
I'd like to say that I have all ready, but I found some Spring specific header inconsistencies and struggling with picking the right approach.

`retainAllRetryHeaderValues` flag in `DeadLetterPublishingRecovererFactory` allows to have multiple headers on Kafka-side for given header types (especially `RetryTopicHeaders.DEFAULT_HEADER_ATTEMPTS`). When these were mapped onto Spring `Message` only the last one was always retained allowing to simply use `@Header(name = RetryTopicHeaders.DEFAULT_HEADER_ATTEMPTS, required = false) Integer nonBlockingAttempts` (as in `DeliveryHeaderTests`). As I was unware of usage of such headers, the current state of my MR allows to map these to a potential List on Spring side.
This has developed into another problem. Spring was still able to map List of values onto a single element with usage of `CollectionToObjectConverter`. The converter is taking first element thought. To overcome this and allow potential backwards compatibility I decided to reverse the list order while mapping.
Current solution is also inconsistent as I decided to keep only last values for headers such as: `KafkaHeaders.DELIVERY_ATTEMPT, KafkaHeaders.LISTENER_INFO, KafkaUtils.KEY_DESERIALIZER_EXCEPTION_HEADER and KafkaUtils.VALUE_DESERIALIZER_EXCEPTION_HEADER` as they where already specified in the `DefaultKafkaHeaderMapper` mapper. When I tried to allow multiple values for `KafkaHeader.DELIVERY_ATTEMPT` multiple test issues arose.

Having said that I'd suggest to keep a list of Spring 'technical' Kafka headers that should never be mapped into a collection on the Spring side (only last values should be kept). This would avoid unnecessary changes in the code (especially in the retrytopic package). If this plus reversing list order (so `CollectionToObjectConverter` can pick up the last value for backwards compatibility) sounds fine to you I can proceed with polishing and providing appropriate documentation.

2024-04-03 21:38 UTC, sobychacko commented
@poznachowski Sorry for the delay in responding to you. The approach you mentioned for keeping the internal metadata type headers as only single-value item makes sense. As long as it doesn't bring any backward compatibility issues, it's ok to reverse the order. Please re-work the PR and when ready, remove the draft status, so that we can start a formal PR review. Thanks!

2024-04-09 15:25 UTC, artembilan requested changes

2024-04-09 15:25 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
> +	 *
Please, consider to not reformat Javadocs: no empty lines for methods.

2024-04-09 15:25 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
> +				jsonHeaders.put(headerIndex == null ?
I'm not sure what you are doing here, but I think all the framework headers must be as a single value Kafka headers anyway. There are a lot of logic in the framework which relies on them.
We just must agree that we have to make a fix only for end-user headers which can be iterable.
Even if that JSON headers looks like a collection, it is really something what the framework rely on as as single header.
So, I don't expect too drastic changes in this area.
Thanks.

2024-06-10 17:58 UTC, sobychacko commented
@poznachowski Are you going to continue working on this PR? We can also consider taking it on our end and start making additional changes on top of your PR. Please let us know the status.

2024-06-21 14:30 UTC, sobychacko commented
@poznachowski, I just wanted to see if there is an update on this PR. If you are busy, we can take this PR and work on it on our end. Please let us know. Thank you.

2024-09-14 01:02 UTC, sobychacko commented
@poznachowski, Any updates on this PR? We are still in the milestone stages of the `3.3.0` release, and if you update the PR, we can potentially include this feature in the RC1 timeline.

2025-05-11 00:53 UTC, artembilan commented
Superseded by https://github.com/spring-projects/spring-kafka/pull/3874.

2025-05-11 00:53 UTC, closed without merging