GH-3409: Improve exceptions during retry
spring-projects/spring-kafka pull request #3421
Opened 2024-08-14 16:48 UTC by sobychacko

Fixes: #3409

- During error handling, records in retry are throwing `KafkaException` after seeking that causes the exception to get logged which maybe misleading. It seems to indicate that the error handling process itself thew the exception, while the exception was thrown in order to prevent accidental committing of a not-yet recovered record. Change this exception during seeks in retry while handling error from `KafkaException` to a new framework-only used exception - `RecordInRetryException` that simply logs the message at INFO level.

2024-08-14 16:54 UTC, artembilan requested changes
And yes: I don't think there is anything to mention in the docs 😄

2024-08-14 16:54 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
> +					rire.selfLog(this.logger);
I wouldn't do this, but just `this.logger.info("BLAH-BLAH", rire)`

2024-08-14 16:54 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/listener/RecordInRetryException.java
> +	}
Just nit-pic: every member in the class must be surrounded with blank lines, even the last method of the last inner class.

2024-08-14 17:45 UTC, merged

2025-05-23 10:24 UTC, Djaler commented
It was unexpected for me to not see listener error logs after upgrading spring in our app.

We have error handler without max retries, so now we don't see errors logs.