GH-3407 : Support KafkaHeaders.DELIVERY_ATTEMP for batch listeners.
spring-projects/spring-kafka pull request #3539
Opened 2024-10-07 11:46 UTC by chickenchickenlove

### Motivation:
The developer expects to get the `KafkaHeaders.DELIVERY_ATTEMPT` header from the received `ConsumerRecord`. 
It works well with the `SingleRecordListener`. 
However, it does not work well with the `BatchListener` even when `containerProperties.setDeliveryAttemptHeader(true)` is set. 
If the `KafkaContainerListener` can include the `KafkaHeaders.DELIVERY_ATTEMPT` header for each `ConsumerRecord` with the `BatchListener`, it will be more helpful to people who they expect.

### Modifications
- Add `DeliveryAttemptAwareRetryListener` class.
- Add unit tests and integration tests for `DeliveryAttemptAwareRetryListener`. 

### To Reviewer
With current `spring-kafka` codes, it is hard to integrate it to `FailedRecordTracker`. 
By the way, the function `ErrorHandlingUtils.retryBatch()` has deliveryAttempt count as their local scope and has same reference for `ConsumerRecord`. 
Thus, the `DeliveryAttemptAwareRetryListener` is easier way to achieve the goal. 
Because, in each fail to invocation, `ErrorHandlingUtils.retryBatch()` calls `listeners.forEach(listener -> listener.failedDelivery(records, thrownException, attempt)`.

If the developer want to use this feature, they should create `ContainerFactory` and `DeliveryAttemptAwareRetryListener`. also, they set `DeliveryAttemptAwareRetryListener` as `RetryListener`. 
Please refer to code below.

```java
final FixedBackOff fixedBackOff = new FixedBackOff(1000L, MAX_ATTEMPT_COUNT1);
DefaultErrorHandler errorHandler = new DefaultErrorHandler(fixedBackOff);
errorHandler.setRetryListeners(new DeliveryAttemptAwareRetryListener());

ConcurrentKafkaListenerContainerFactory<String, String> factory = new ConcurrentKafkaListenerContainerFactory<>();
factory.setConsumerFactory(consumerFactory);
factory.setCommonErrorHandler(errorHandler);
```

### Result:
- Fixes https://github.com/spring-projects/spring-kafka/issues/3407

2024-10-07 13:41 UTC, artembilan requested changes
I see now how this makes sense.
Thank you for fixing it!

Please, consider to mention a new feature in the docs, including a short entry with a link into target doc in the `whats-new.adoc`.

2024-10-07 13:41 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/listener/DeliveryAttemptAwareRetryListener.java
> +	 * Called after a delivery failed for batch records.
The method JavaDoc must be imperative. So, `Call after`.

2024-10-07 13:41 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/listener/DeliveryAttemptAwareRetryListener.java
> +	 *
No blank lines in the method JavaDoc

2024-10-07 13:41 UTC, artembilan commented on spring-kafka/src/main/java/org/springframework/kafka/listener/DeliveryAttemptAwareRetryListener.java
> +				headerCount += 1;
I think just `headers.remove(KafkaHeaders.DELIVERY_ATTEMPT)` is enough.
No need to do this extra loop.
You just don't check the content of the header, but fully override it.

2024-10-07 13:41 UTC, artembilan commented on spring-kafka/src/test/java/org/springframework/kafka/listener/DeliveryAttemptAwareRetryListenerIntegrationTest.java
> +class DeliveryAttemptAwareRetryListenerIntegrationTest {
All the test must be called `*Tests`

2024-10-07 13:41 UTC, artembilan commented on spring-kafka/src/test/java/org/springframework/kafka/listener/DeliveryAttemptAwareRetryListenerTest.java
> +class DeliveryAttemptAwareRetryListenerTest {
DITTO.

2024-10-08 12:13 UTC, chickenchickenlove commented
@artembilan thanks for your time and comments! 
I made a new commit to apply your comments.
When you have time, please take another look 🙇‍♂️

2024-10-08 16:26 UTC, artembilan requested changes

2024-10-08 16:26 UTC, artembilan commented on spring-kafka/src/test/java/org/springframework/kafka/listener/DeliveryAttemptAwareRetryListenerIntegrationTests.java
> +			return factory;
Apparently a common code for both these two bean could be extracted to `private` method for better readability.

2024-10-09 00:14 UTC, chickenchickenlove commented
@artembilan thanks for your time for looking into changes, again! 🙇‍♂️ 
I made a new commit to apply your comments.
When you have time, please take another look! 

Always thanks to read my code 🙇‍♂️

2024-10-09 14:19 UTC, artembilan commented on spring-kafka/src/test/java/org/springframework/kafka/listener/DeliveryAttemptAwareRetryListenerIntegrationTests.java
> +			props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
The `value.serializer` is a `StringSerializer` by default in the `KafkaTestUtils.producerProps()`.
And why do we really need a `StringSerializer` for key in these tests?
Why cannot we just rely on the defaults from the `KafkaTestUtils.producerProps()`?

2024-10-09 14:20 UTC, artembilan commented on spring-kafka/src/test/java/org/springframework/kafka/listener/DeliveryAttemptAwareRetryListenerIntegrationTests.java
> +			props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
Something similar for `KafkaTestUtils.consumerProps()`.
Why we just cannot rely on the defaults from there?
And why do we really need that `ConsumerConfig.ALLOW_AUTO_CREATE_TOPICS_CONFIG`?

2024-10-09 22:10 UTC, chickenchickenlove commented
@artembilan , It's my bad! 
I cleaned up the code that I thought was useless.
When you have time, please take another look 🙇‍♂️

2024-10-10 16:05 UTC, merged

2024-10-10 16:10 UTC, artembilan commented
Thank you, @chickenchickenlove , again for contribution!

Please, take a look into this article about commit messages: https://cbea.ms/git-commit/.
Also take into account that first commit message becomes PR description automatically. 
Just for a sake to save some yours and ours time:
- first - no need to write separate PR description
- second - no need to write extra commit message on merge
- and last - the commit message is exactly what we always need to be good. The PR easily might be lost, but commit is there forever.

Now imaging time is passing and we don't have contacts with you to remind us whatever was done in that commit years ago.
but if you write a good commit message, it will be merged there into a history with respective honor outcome.

2024-10-10 21:52 UTC, chickenchickenlove commented
Thanks for your time 🙇‍♂️ 
As you mentioned, I will try to write good commit message 👍