Fix flaky tests in async retry by using a latch instead of sleep.
spring-projects/spring-kafka pull request #3563
Opened 2024-10-18 14:19 UTC by chickenchickenlove

### Motivation
In the previous version, all test cases depended on sleep.
However, it made all test cases flaky. 

### Modification
- Removed sleep.
- Used latch instead.

### Result
- Fixes flaky test cases in `AsyncCompletableFutureRetryTopicScenarioTests`, `AsyncMonoRetryTopicScenarioTests`.

2024-10-18 14:28 UTC, artembilan requested changes
Thank you for looking into this @chickenchickenlove !

If you think it is OK now, then consider to remove that `@DisabledIfEnvironmentVariable` in the `AsyncCompletableFutureRetryTopicScenarioTests`.

2024-10-18 14:36 UTC, artembilan requested changes
You have missed to remove an `import org.junit.jupiter.api.condition.DisabledIfEnvironmentVariable;`.
It is still going to fail for Checkstyle.
That's why it is better to run `./gradlew check` locally before pushing changes to the PR.

2024-10-18 14:52 UTC, artembilan requested changes
Looks like it is not OK yet:
```
AsyncCompletableFutureRetryTopicScenarioTests > moreComplexAsyncScenarioTest(TestTopicListener6, MyCustomDltProcessor) FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting actual:
      ["fail0",
        "success1",
        "success2",
        "fail3",
        "success4",
        "fail0",
        "fail3",
        "fail0",
        "fail3"]
    to contain exactly (and in same order):
      ["fail0",
        "success1",
        "success2",
        "fail3",
        "success4",
        "fail3",
        "fail3",
        "fail0",
        "fail0"]
    but there were differences at these indexes:
      - element at index 5: expected "fail3" but was "fail0"
      - element at index 8: expected "fail0" but was "fail3"
        at java.base@17.0.12/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base@17.0.12/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base@17.0.12/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base@17.0.12/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at app//org.springframework.kafka.retrytopic.AsyncCompletableFutureRetryTopicScenarioTests.moreComplexAsyncScenarioTest(AsyncCompletableFutureRetryTopicScenarioTests.java:572)
```

2024-10-18 15:32 UTC, merged

2024-10-18 15:37 UTC, chickenchickenlove commented
Thanks for your review, and I apologize for the inconvenience 🙇‍♂️. 
I decided to use `containsExactlyInAnyOther()` instead of `containsExactly()`.
Because, I think an issue which i cannot control seems occurs when `kafkaTemplate.send(...)`

2024-10-21 10:42 UTC, artembilan commented
Looks like some are still non-stable: https://github.com/spring-projects/spring-kafka/actions/runs/11433571335/job/31805772798. Feel free to disable them or remove altogether .

2024-10-21 11:17 UTC, chickenchickenlove commented
@artembilan , sorry to bother you.
I will remove test codes which required long test times. 
Please wait an hour, i'm in office time. i will create a PR!

2024-10-21 11:23 UTC, artembilan commented
@chickenchickenlove , no rush. Just sharing with you a status. I don’t think those tests are failing because of some bug in the production code, but more as a design flaw of the tests themselves. Sometimes we are really just cannot model the situation and verify it at the same time. So, that is better to be present as a sample application .
But again : this does not stop us to move on and we can live with the current status a bit.