GH-3617 : Value parameters in ReactiveKafkaProducerTemplate should be nullable
spring-projects/spring-kafka pull request #3651
Opened 2024-11-26 16:33 UTC by kimjuke

* Fixes : #3617 
* add @Nullable to parameter of send method
* Fix to allow tombstone records to be transferred.

2024-11-26 16:33 UTC, pivotal-cla commented
@kimjuke Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=3651)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=3651) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-11-26 16:33 UTC, pivotal-cla commented
@kimjuke Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=3651)!

2024-11-27 20:37 UTC, sobychacko requested changes
Could you add your name to the author list?

2024-11-28 11:13 UTC, kimjuke commented on spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplate.java
> +import reactor.util.annotation.Nullable;
Thanks for your review!
I modified the package as you mentioned.

2024-11-28 11:16 UTC, kimjuke commented
> Could you add your name to the author list?

i added my name, Thank you.

2024-12-03 20:51 UTC, sobychacko approved these changes

2024-12-03 21:21 UTC, sobychacko commented
PR is failing due to checkstyle errors. Can you fix those?
```
Error: eckstyle] [ERROR] /home/runner/work/spring-kafka/spring-kafka/spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplate.java:29:1: 'org.springframework.lang.Nullable' should be separated from previous imports. [ImportOrder]

Error: eckstyle] [ERROR] /home/runner/work/spring-kafka/spring-kafka/spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplate.java:30:1: Wrong order for 'reactor.core.publisher.Flux' import. [ImportOrder]
```

2024-12-04 14:48 UTC, jukekxm commented
> PR is failing due to checkstyle errors. Can you fix those?
> 
> ```
> Error: eckstyle] [ERROR] /home/runner/work/spring-kafka/spring-kafka/spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplate.java:29:1: 'org.springframework.lang.Nullable' should be separated from previous imports. [ImportOrder]
> 
> Error: eckstyle] [ERROR] /home/runner/work/spring-kafka/spring-kafka/spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplate.java:30:1: Wrong order for 'reactor.core.publisher.Flux' import. [ImportOrder]
> ```

I fixed them. Thank You :)

2024-12-07 23:49 UTC, merged

2024-12-07 23:49 UTC, sobychacko commented
@jukekxm Thanks for the PR. It is now merged upstream.